#!/usr/bin/env python3
"""
Generate a SYNTHETIC home directory for the demo. Nothing here is real.

It writes, under --home (default: data/demo/home):

  .claude/projects/…/*.jsonl   Claude Code transcripts: several models and days,
                               assistant messages split into 2-3 lines that
                               share the same `message.id` and `usage` (the
                               real format that caused the x2.3 overcount),
                               nested subagent transcripts, tool_use blocks
                               (Edit, Bash, Skill, Task, MCP), noisy "user"
                               lines, and one rate-limit rejection.
  .claude/projects/…/memory    memory notes with [[links]] (one broken)
  .claude/{skills,agents,plugins}, .claude.json, a project .mcp.json
  .codex/sessions/…            Codex rollouts with cumulative + per-turn usage
  .hermes/state.db             a minimal Hermes database (token_count = 0)
  .hermes/{skills/.usage.json,memories}
  .openclaw/openclaw.json
  Notes/                       a markdown vault with [[links]] (one broken)
  Library/LaunchAgents/*.plist

  --rotate  replaces one transcript with new content at the same path
            (new inode), to show the reader re-reading a rotated file.

Invented projects, example.com addresses, no real person or company.
Timestamps are relative to "now" so the dashboard windows have data.
Only the standard library.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import plistlib
import random
import sqlite3
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOW = dt.datetime.now(dt.timezone.utc).replace(microsecond=0)

PROJECTS = ["acme-webshop", "ledger-api", "notes-cli"]
CWD = "/home/demo/projects/{}"
FOLDER = "-home-demo-projects-{}"

PROMPTS = [
    "Add email validation to the sign-up form (use alice@example.com in the tests)",
    "Refactor the cart tax calculation so it accepts several countries",
    "Why does the /invoices endpoint fail with a 500 when the date is empty",
    "Write a script that migrates the Globex Ltd test customers to the new schema",
    "Document in the README how to start the local database with docker",
    "Raise the coverage of the payments module above 80%",
    "Change the checkout button copy and check the contrast",
    "Prepare the release notes for version 0.4 from the latest commits",
    "Find where the queue connection is created and add retries with backoff",
    "Make the CLI accept --json and keep the output readable by default",
]
# A repeated opening: the pattern detector must see it (>= 4 in 14 days).
# Every prompt above starts differently in its first 18 characters, which is
# what the detector groups by.
REPEATED = "Review the failing tests in {} and fix them without touching the public API"
NOISE = ["<command-name>/clear</command-name>", "[image: screenshot-2026.png]",
         "Caveat: the messages below were generated by the user while running local commands"]

SKILLS = ["release-notes", "db-migrations", "api-docs", "changelog-writer", "pdf-export",
          "ui-audit", "perf-budget", "i18n-check", "sql-review", "k8s-deploy",
          "incident-report", "seo-meta"]
USED_SKILLS = ["release-notes", "sql-review"]
AGENTS = ["code-reviewer", "test-writer", "doc-scribe", "security-auditor"]


def iso(t: dt.datetime) -> str:
    return t.strftime("%Y-%m-%dT%H:%M:%S.") + f"{t.microsecond // 1000:03d}Z"


class Gen:
    def __init__(self, home: Path, seed: int):
        self.home = home
        self.r = random.Random(seed)

    def uid(self) -> str:
        return str(uuid.UUID(int=self.r.getrandbits(128), version=4))

    def write(self, path: Path, text: str | bytes, mtime: dt.datetime | None = None):
        path.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(text, bytes):
            path.write_bytes(text)
        else:
            path.write_text(text)
        if mtime is not None:
            os.utime(path, (mtime.timestamp(), mtime.timestamp()))

    # ── Claude Code ──────────────────────────────────────────────────────
    def assistant_turn(self, lines, base, t, model, *, good_cache=True, fast=False,
                       tools=(), output=None, sidechain=False):
        """One assistant message written as 2-3 JSONL lines sharing id and usage."""
        mid = "msg_" + uuid.UUID(int=self.r.getrandbits(128)).hex[:24]
        output = output if output is not None else self.r.choice(
            [self.r.randint(40, 340), self.r.randint(400, 1800)])
        if good_cache:
            read, inp = self.r.randint(30_000, 90_000), self.r.randint(3, 60)
        else:
            read, inp = self.r.randint(500, 4_000), self.r.randint(8_000, 25_000)
        usage = {
            "input_tokens": inp, "output_tokens": output,
            "cache_read_input_tokens": read,
            "cache_creation": {"ephemeral_5m_input_tokens": self.r.randint(0, 6_000),
                               "ephemeral_1h_input_tokens": self.r.choice([0, 0, 12_000])},
        }
        if fast:
            usage["speed"] = "fast"
        blocks = [{"type": "text", "text": "Done. Here is what changed."}]
        for h in tools:
            blocks.append(self.block(h))
        # 30% of messages come as 3 lines, 70% as 2 → ~2.3 lines per message.
        # This is a DESIGN CHOICE that mimics the duplication seen in real
        # transcripts; the demo illustrates the dedup, it does not discover it.
        parts = 3 if self.r.random() < 0.3 else 2
        for i in range(parts):
            b = blocks[i] if i < len(blocks) else {"type": "text", "text": "…"}
            lines.append({**base, "type": "assistant", "uuid": self.uid(),
                          "timestamp": iso(t + dt.timedelta(milliseconds=40 * i)),
                          "isSidechain": sidechain,
                          "message": {"id": mid, "role": "assistant", "model": model,
                                      "content": [b], "usage": usage}})
        # Any tool_use block beyond the lines above still has to appear once.
        for b in blocks[parts:]:
            lines.append({**base, "type": "assistant", "uuid": self.uid(), "timestamp": iso(t),
                          "isSidechain": sidechain,
                          "message": {"id": mid, "role": "assistant", "model": model,
                                      "content": [b], "usage": usage}})

    def block(self, h: str) -> dict:
        tid = "toolu_" + uuid.UUID(int=self.r.getrandbits(128)).hex[:20]
        if h.startswith("skill:"):
            return {"type": "tool_use", "id": tid, "name": "Skill", "input": {"skill": h[6:]}}
        if h.startswith("agent:"):
            return {"type": "tool_use", "id": tid, "name": "Task",
                    "input": {"subagent_type": h[6:], "prompt": "Review the diff"}}
        return {"type": "tool_use", "id": tid, "name": h, "input": {}}

    def claude_session(self, project, start, turns, model, *, style="normal",
                       fixed_prompt=None, rate_limit=False, name=None):
        sid = self.uid()
        base = {"sessionId": sid, "cwd": CWD.format(project), "version": "2.1.0",
                "gitBranch": self.r.choice(["main", "feature/checkout", "fix/invoices"])}
        lines: list[dict] = []
        t = start
        for i in range(turns):
            if i % 6 == 0:
                text = (fixed_prompt if (fixed_prompt and i == 0)
                        else self.r.choice(PROMPTS))
                lines.append({**base, "type": "user", "uuid": self.uid(), "timestamp": iso(t),
                              "message": {"role": "user", "content": text}})
                if self.r.random() < 0.15:
                    lines.append({**base, "type": "user", "uuid": self.uid(), "timestamp": iso(t),
                                  "message": {"role": "user", "content": self.r.choice(NOISE)}})
            if style == "edits":             # builds without planning
                hs = [self.r.choice(["Edit", "Write", "Edit", "Read"])]
            elif style == "plans":
                hs = ["TodoWrite"] if i == 0 else [self.r.choice(["Edit", "Read", "Grep"])]
            elif style == "bash":            # many shell calls, no skill
                hs = ["Bash"]
            else:
                hs = [self.r.choice(["Read", "Grep", "Bash", "Edit"])]
                if self.r.random() < 0.04:
                    hs.append("skill:" + self.r.choice(USED_SKILLS))
                if self.r.random() < 0.03:
                    hs.append("agent:code-reviewer")
                if self.r.random() < 0.05:
                    hs.append(self.r.choice(["mcp__github__create_issue", "mcp__playwright__navigate",
                                             "mcp__linear__list_issues"]))
            self.assistant_turn(
                lines, base, t, model,
                good_cache=(project != "notes-cli"),
                fast=(model == "claude-opus-5" and self.r.random() < 0.05),
                tools=hs,
                output=self.r.randint(900, 2400) if style == "marathon" else None,
            )
            t += dt.timedelta(seconds=self.r.randint(20, 140))
            if t > NOW - dt.timedelta(minutes=5):
                break
        if rate_limit:
            lines.append({**base, "type": "system", "uuid": self.uid(), "timestamp": iso(t),
                          "message": {"quotaLimits": {
                              "status": "rejected", "rateLimitType": "five_hour",
                              "resetsAt": int((t + dt.timedelta(hours=2)).timestamp()),
                              "overageStatus": "disabled", "overageDisabledReason": "out_of_credits"}}})
        folder = self.home / ".claude" / "projects" / FOLDER.format(project)
        path = folder / f"{name or sid}.jsonl"
        self.write(path, "".join(json.dumps(x, ensure_ascii=False) + "\n" for x in lines))
        return sid, folder, t

    def subagent(self, folder: Path, sid: str, project: str, start: dt.datetime):
        base = {"sessionId": sid, "cwd": CWD.format(project), "gitBranch": "main"}
        lines: list[dict] = []
        t = start
        for _ in range(self.r.randint(6, 14)):
            self.assistant_turn(lines, base, t, "claude-sonnet-5", tools=["Read"],
                                sidechain=True)
            t += dt.timedelta(seconds=15)
        path = folder / sid / "subagents" / f"agent-{self.uid()[:8]}.jsonl"
        self.write(path, "".join(json.dumps(x) + "\n" for x in lines))

    def claude_code(self):
        # 27 days of normal work, one or two sessions a day.
        for days in range(27, 0, -1):
            for _ in range(self.r.choice([1, 1, 2])):
                day = NOW - dt.timedelta(days=days, hours=self.r.randint(1, 10))
                recent = days <= 7
                project = ("acme-webshop" if recent and self.r.random() < 0.8
                           else self.r.choice(PROJECTS))
                model = self.r.choices(
                    ["claude-opus-5", "claude-sonnet-5", "claude-haiku-4-5", "claude-lab-preview"],
                    weights=[6, 3, 1, 0.4])[0]
                style = ("edits" if recent and self.r.random() < 0.5
                         else "bash" if days <= 12 and self.r.random() < 0.25 else "normal")
                prompt = REPEATED.format(project) if days <= 12 and self.r.random() < 0.35 else None
                sid, folder, _ = self.claude_session(project, day, self.r.randint(18, 60), model,
                                                     style=style, fixed_prompt=prompt)
                if self.r.random() < 0.3:
                    self.subagent(folder, sid, project, day + dt.timedelta(minutes=5))
        # Guaranteed repetitions for the pattern detector.
        for k in range(4):
            day = NOW - dt.timedelta(days=2 + k, hours=3)
            self.claude_session("ledger-api", day, 12, "claude-sonnet-5",
                                fixed_prompt=REPEATED.format("ledger-api"))
        # Sessions that build without a plan, and ones driven by Bash alone.
        for k in range(4):
            self.claude_session("acme-webshop", NOW - dt.timedelta(days=1 + k, hours=5), 20,
                                "claude-opus-5", style="edits")
        for k in range(2):
            self.claude_session("notes-cli", NOW - dt.timedelta(days=3 + k, hours=2), 32,
                                "claude-opus-5", style="bash")
        # A marathon session that also hits the 5-hour limit.
        self.claude_session("acme-webshop", NOW - dt.timedelta(hours=30), 430, "claude-opus-5",
                            style="marathon", rate_limit=True)
        # The file that --rotate will replace later.
        self.claude_session("ledger-api", NOW - dt.timedelta(days=1, hours=2), 10,
                            "claude-sonnet-5", name="rotated-session")

    def rotate(self):
        path = (self.home / ".claude" / "projects" / FOLDER.format("ledger-api")
                / "rotated-session.jsonl")
        before = path.stat().st_ino if path.exists() else None
        tmp = path.with_suffix(".new")
        self.r.seed(os.getpid())            # new content, new message ids
        folder = path.parent
        _, _, _ = self.claude_session("ledger-api", NOW - dt.timedelta(hours=1), 8,
                                      "claude-haiku-4-5", name="rotated-session.new")
        (folder / "rotated-session.new.jsonl").rename(tmp)
        os.replace(tmp, path)               # same path, new inode
        print(f"rotated {path.name}: inode {before} -> {path.stat().st_ino}")

    # ── Claude config, memory, inventory ─────────────────────────────────
    def claude_config(self):
        c = self.home
        self.write(c / ".claude.json", json.dumps({
            "oauthAccount": {"organizationRateLimitTier": "default_claude_pro",
                             "organizationType": "claude_pro",
                             "subscriptionCreatedAt": "2026-01-15T09:00:00Z",
                             "hasExtraUsageEnabled": True,
                             "emailAddress": "demo@example.com"},
            "cachedExtraUsageDisabledReason": "out_of_credits",
            "claudeAiMcpEverConnected": ["claude.ai Notion", "claude.ai Linear", "claude.ai Gmail"],
            "mcpServers": {"github": {"command": "npx", "args": ["-y", "github-mcp"],
                                      "env": {"GITHUB_TOKEN": ""}}},
        }, indent=2))
        self.write(c / "projects" / "acme-webshop" / ".mcp.json", json.dumps({
            "mcpServers": {"playwright": {"command": "npx"},
                           "postgres-local": {"command": "docker", "env": {"PGPASSWORD": ""}}}
        }, indent=2))
        for i, s in enumerate(SKILLS):
            d = NOW - dt.timedelta(days=5 + i * 3)
            self.write(c / ".claude" / "skills" / s / "SKILL.md",
                       f"---\nname: {s}\ndescription: Synthetic example skill ({s}).\n---\n\n# {s}\n", d)
        for a in AGENTS:
            self.write(c / ".claude" / "agents" / f"{a}.md",
                       f"---\nname: {a}\ndescription: Synthetic subagent.\nmodel: sonnet\n---\n")
        self.write(c / ".claude" / "plugins" / "installed_plugins.json", json.dumps({"plugins": {
            "lint-helper@example-market": [{"installPath": str(c / ".claude/plugins/cache/lint-helper"),
                                            "version": "1.2.0", "lastUpdated": iso(NOW)}]}}))

    def memory(self):
        c = self.home
        notes = {
            # claude-mem system: per-project memory
            c / ".claude/projects" / FOLDER.format("acme-webshop") / "memory/MEMORY.md":
                ("Index: [[checkout-decisions]] · [[style-guide]]", 1),
            c / ".claude/projects" / FOLDER.format("acme-webshop") / "memory/checkout-decisions.md":
                ("We keep taxes server-side. See [[style-guide]].", 3),
            c / ".claude/projects" / FOLDER.format("acme-webshop") / "memory/style-guide.md":
                ("Use the design tokens. Contact: design@example.com", 26),
            c / ".claude/projects" / FOLDER.format("ledger-api") / "memory/MEMORY.md":
                ("Index: [[invoice-rules]] · [[old-deploy-notes]]", 14),
            c / ".claude/projects" / FOLDER.format("ledger-api") / "memory/invoice-rules.md":
                ("Invoices for Initech Corp use net-30.", 33),
            # an Obsidian-style vault (MOTOR_NOTES)
            c / "Notes/00 Home.md": ("[[Projects]] · [[Reading list]] · [[Missing note]]", 0),
            c / "Notes/Projects.md": ("[[acme roadmap]] and [[ledger decisions]]", 2),
            c / "Notes/projects/acme roadmap.md": ("Q4: checkout v2. Back to [[Projects]]", 12),
            c / "Notes/projects/ledger decisions.md": ("Decision log. [[Projects]]", 40),
            c / "Notes/Reading list.md": ("Nothing here yet.", 61),
            # Hermes memories
            c / ".hermes/memories/user-profile.md": ("Prefers short answers.", 4),
            c / ".hermes/memories/session-2026-08-20.md": ("Old session summary.", 25),
        }
        for path, (text, days) in notes.items():
            self.write(path, f"# {path.stem}\n\n{text}\n", NOW - dt.timedelta(days=days))

    # ── Codex ────────────────────────────────────────────────────────────
    def codex(self):
        for k in range(7):
            t = NOW - dt.timedelta(days=2 + k * 3, hours=4)
            sid = self.uid()
            model = "gpt-5.6-preview" if k == 5 else "gpt-5-codex"
            project = self.r.choice(PROJECTS)
            path = (self.home / ".codex/sessions" / t.strftime("%Y/%m/%d")
                    / f"rollout-{t.strftime('%Y-%m-%dT%H-%M-%S')}-{sid}.jsonl")
            lines = [{"timestamp": iso(t), "type": "session_meta",
                      "payload": {"id": sid, "cwd": CWD.format(project), "model": model}}]
            total = {"input_tokens": 0, "cached_input_tokens": 0, "output_tokens": 0,
                     "reasoning_output_tokens": 0, "total_tokens": 0}
            for i in range(self.r.randint(8, 20)):
                t += dt.timedelta(seconds=self.r.randint(30, 90))
                last = {"input_tokens": self.r.randint(2_000, 9_000),
                        "cached_input_tokens": self.r.randint(10_000, 40_000),
                        "output_tokens": self.r.randint(200, 1_500),
                        "reasoning_output_tokens": self.r.randint(0, 800)}
                last["total_tokens"] = last["input_tokens"] + last["output_tokens"]
                for key in total:
                    total[key] += last[key]
                if i == 0:
                    lines.append({"timestamp": iso(t), "type": "turn_context",
                                  "payload": {"model": model, "cwd": CWD.format(project)}})
                lines.append({"timestamp": iso(t), "type": "event_msg",
                              "payload": {"type": "token_count",
                                          "info": {"total_token_usage": dict(total),
                                                   "last_token_usage": last}}})
            self.write(path, "".join(json.dumps(x) + "\n" for x in lines))

    # ── Hermes and OpenClaw ──────────────────────────────────────────────
    def hermes(self):
        h = self.home / ".hermes"
        h.mkdir(parents=True, exist_ok=True)
        db = h / "state.db"
        if db.exists():
            db.unlink()
        cx = sqlite3.connect(db)
        cx.executescript("""
            CREATE TABLE sessions (id TEXT PRIMARY KEY, source TEXT, model TEXT,
                                   session_key TEXT, display_name TEXT);
            CREATE TABLE messages (id INTEGER PRIMARY KEY, session_id TEXT, role TEXT,
                                   content TEXT, timestamp REAL, token_count INTEGER DEFAULT 0);
        """)
        titles = ["Daily backlog summary", "Draft reply to vendor@example.com",
                  "Weekly metrics digest", "Research: queue backoff strategies",
                  "Reminder list", "Changelog draft for notes-cli"]
        for k, title in enumerate(titles):
            sid = f"hs_{k:03d}"
            cx.execute("INSERT INTO sessions VALUES (?,?,?,?,?)",
                       (sid, "telegram" if k % 2 else "cli",
                        "nousresearch/hermes-4-70b" if k % 3 else "openai/gpt-5-mini",
                        f"demo:{k}", title))
            t = (NOW - dt.timedelta(days=1 + k * 2)).timestamp()
            for m in range(self.r.randint(4, 16)):
                cx.execute("INSERT INTO messages (session_id, role, content, timestamp, token_count)"
                           " VALUES (?,?,?,?,0)",
                           (sid, "user" if m % 2 == 0 else "assistant", "synthetic message", t + m * 45))
        cx.commit()
        cx.close()
        self.write(h / "skills/.usage.json", json.dumps({
            "web-research": {"use_count": 9, "last_used_at": iso(NOW - dt.timedelta(days=1)),
                             "created_at": "2026-07-01T10:00:00Z"},
            "daily-digest": {"use_count": 21, "last_used_at": iso(NOW - dt.timedelta(hours=20)),
                             "created_at": "2026-07-03T10:00:00Z"},
            "pdf-summary": {"use_count": 0, "last_used_at": None, "created_at": "2026-08-01T10:00:00Z"},
        }, indent=2))

    def openclaw(self):
        self.write(self.home / ".openclaw/openclaw.json", json.dumps({
            "agents": {"defaults": {"model": {"primary": "openrouter/anthropic/claude-sonnet-5"}},
                       "list": [{"id": "triage", "description": "Sorts inbound issues by label"},
                                {"id": "docs-writer", "description": "Drafts docs pages",
                                 "model": "openrouter/openai/gpt-5-mini"}]}}, indent=2))

    def launchd(self):
        folder = self.home / "Library/LaunchAgents"
        agents = {
            "com.example.motor.reader": {"RunAtLoad": True, "KeepAlive": True,
                                         "ProgramArguments": ["/usr/bin/python3",
                                                              "/opt/motor/reader/reader.py", "--loop"]},
            "com.example.motor.review": {"StartCalendarInterval": {"Hour": 7, "Minute": 0},
                                         "ProgramArguments": ["/usr/bin/python3",
                                                              "/opt/motor/reader/review.py"]},
            "com.example.backup": {"StartInterval": 3600, "ProgramArguments": ["/usr/local/bin/backup"]},
        }
        for label, d in agents.items():
            self.write(folder / f"{label}.plist", plistlib.dumps({"Label": label, **d}))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--home", type=Path, default=ROOT / "data" / "demo" / "home")
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--rotate", action="store_true", help="only rotate the demo transcript")
    a = ap.parse_args()
    g = Gen(a.home.resolve(), a.seed)
    if a.rotate:
        g.rotate()
        return
    g.claude_config()
    g.claude_code()
    g.memory()
    g.codex()
    g.hermes()
    g.openclaw()
    g.launchd()
    n = sum(1 for _ in g.home.rglob("*") if _.is_file())
    print(f"synthetic home ready: {n} files under {a.home}")


if __name__ == "__main__":
    main()
