#!/usr/bin/env python3
"""
Generate a SYNTHETIC home directory for the demo. Nothing here is real.

It writes, under --casa (default: data/demo/home):

  .claude/projects/…/*.jsonl   Claude Code transcripts: several models and days,
                               assistant messages split into 2-3 lines that
                               share the same `message.id` and `usage` (the
                               real format that caused the x2.3 overcount),
                               nested subagent transcripts, tool_use blocks
                               (Edit, Bash, Skill, Task, MCP), noisy "user"
                               lines, and one rate-limit rejection.
  .claude/projects/…/memory    memory notes with [[links]] (one broken)
  .claude/{skills,agents,plugins}, .claude.json, a project .mcp.json
  .codex/sessions/…            Codex rollouts with cumulative + per-turn usage
  .hermes/state.db             a minimal Hermes database (token_count = 0)
  .hermes/{skills/.usage.json,memories}
  .openclaw/openclaw.json
  Notes/                       a markdown vault with [[links]] (one broken)
  Library/LaunchAgents/*.plist

  --rotar   replaces one transcript with new content at the same path
            (new inode), to show the reader re-reading a rotated file.

Invented projects, example.com addresses, no real person or company.
Timestamps are relative to "now" so the dashboard windows have data.
Only the standard library.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import plistlib
import random
import sqlite3
import uuid
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent
AHORA = dt.datetime.now(dt.timezone.utc).replace(microsecond=0)

PROYECTOS = ["acme-webshop", "ledger-api", "notes-cli"]
CWD = "/home/demo/projects/{}"
CARPETA = "-home-demo-projects-{}"

PROMPTS = [
    "Añade validación de email al formulario de alta (usa alice@example.com en los tests)",
    "Refactoriza el cálculo de impuestos del carrito para que acepte varios países",
    "Por qué falla el endpoint /invoices con un 500 cuando la fecha viene vacía",
    "Escribe un script que migre los clientes de prueba de Globex Ltd al esquema nuevo",
    "Documenta en el README cómo levantar la base local con docker",
    "Sube la cobertura del módulo de pagos por encima del 80%",
    "Cambia el copy del botón de checkout y revisa el contraste",
    "Prepara las notas de la versión 0.4 a partir de los últimos commits",
    "Busca dónde se crea la conexión a la cola y añade reintentos con backoff",
    "Haz que el CLI acepte --json y mantén la salida legible por defecto",
]
# Un arranque que se repite: el detector de patrones debe verlo (>= 4 en 14 días).
REPETIDO = "Revisa los tests que fallan en {} y arréglalos sin tocar la API pública"
RUIDO = ["<command-name>/clear</command-name>", "[image: captura-2026.png]",
         "Caveat: the messages below were generated by the user while running local commands"]

SKILLS = ["release-notes", "db-migrations", "api-docs", "changelog-writer", "pdf-export",
          "ui-audit", "perf-budget", "i18n-check", "sql-review", "k8s-deploy",
          "incident-report", "seo-meta"]
SKILLS_USADAS = ["release-notes", "sql-review"]
AGENTES = ["code-reviewer", "test-writer", "doc-scribe", "security-auditor"]


def iso(t: dt.datetime) -> str:
    return t.strftime("%Y-%m-%dT%H:%M:%S.") + f"{t.microsecond // 1000:03d}Z"


class Gen:
    def __init__(self, casa: Path, semilla: int):
        self.casa = casa
        self.r = random.Random(semilla)

    def uid(self) -> str:
        return str(uuid.UUID(int=self.r.getrandbits(128), version=4))

    def escribir(self, ruta: Path, texto: str | bytes, mtime: dt.datetime | None = None):
        ruta.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(texto, bytes):
            ruta.write_bytes(texto)
        else:
            ruta.write_text(texto)
        if mtime is not None:
            os.utime(ruta, (mtime.timestamp(), mtime.timestamp()))

    # ── Claude Code ──────────────────────────────────────────────────────
    def turno_asistente(self, lineas, base, t, modelo, *, cache_bueno=True, rapido=False,
                        herramientas=(), salida=None, sidechain=False):
        """One assistant message written as 2-3 JSONL lines sharing id and usage."""
        mid = "msg_" + uuid.UUID(int=self.r.getrandbits(128)).hex[:24]
        salida = salida if salida is not None else self.r.choice(
            [self.r.randint(40, 340), self.r.randint(400, 1800)])
        if cache_bueno:
            lee, entrada = self.r.randint(30_000, 90_000), self.r.randint(3, 60)
        else:
            lee, entrada = self.r.randint(500, 4_000), self.r.randint(8_000, 25_000)
        usage = {
            "input_tokens": entrada, "output_tokens": salida,
            "cache_read_input_tokens": lee,
            "cache_creation": {"ephemeral_5m_input_tokens": self.r.randint(0, 6_000),
                               "ephemeral_1h_input_tokens": self.r.choice([0, 0, 12_000])},
        }
        if rapido:
            usage["speed"] = "fast"
        bloques = [{"type": "text", "text": "Hecho. Te explico los cambios."}]
        for h in herramientas:
            bloques.append(self.bloque(h))
        # 30% of messages come as 3 lines, 70% as 2 → ~2.3 lines per message.
        # This is a DESIGN CHOICE that mimics the duplication seen in real
        # transcripts; the demo illustrates the dedup, it does not discover it.
        partes = 3 if self.r.random() < 0.3 else 2
        for i in range(partes):
            b = bloques[i] if i < len(bloques) else {"type": "text", "text": "…"}
            lineas.append({**base, "type": "assistant", "uuid": self.uid(),
                           "timestamp": iso(t + dt.timedelta(milliseconds=40 * i)),
                           "isSidechain": sidechain,
                           "message": {"id": mid, "role": "assistant", "model": modelo,
                                       "content": [b], "usage": usage}})
        # Any tool_use block beyond the lines above still has to appear once.
        for b in bloques[partes:]:
            lineas.append({**base, "type": "assistant", "uuid": self.uid(), "timestamp": iso(t),
                           "isSidechain": sidechain,
                           "message": {"id": mid, "role": "assistant", "model": modelo,
                                       "content": [b], "usage": usage}})

    def bloque(self, h: str) -> dict:
        tid = "toolu_" + uuid.UUID(int=self.r.getrandbits(128)).hex[:20]
        if h.startswith("skill:"):
            return {"type": "tool_use", "id": tid, "name": "Skill", "input": {"skill": h[6:]}}
        if h.startswith("agente:"):
            return {"type": "tool_use", "id": tid, "name": "Task",
                    "input": {"subagent_type": h[7:], "prompt": "Revisa el diff"}}
        return {"type": "tool_use", "id": tid, "name": h, "input": {}}

    def sesion_claude(self, proyecto, inicio, turnos, modelo, *, estilo="normal",
                      prompt_fijo=None, tope=False, nombre=None):
        sid = self.uid()
        base = {"sessionId": sid, "cwd": CWD.format(proyecto), "version": "2.1.0",
                "gitBranch": self.r.choice(["main", "feature/checkout", "fix/invoices"])}
        lineas: list[dict] = []
        t = inicio
        for i in range(turnos):
            if i % 6 == 0:
                texto = (prompt_fijo if (prompt_fijo and i == 0)
                         else self.r.choice(PROMPTS))
                lineas.append({**base, "type": "user", "uuid": self.uid(), "timestamp": iso(t),
                               "message": {"role": "user", "content": texto}})
                if self.r.random() < 0.15:
                    lineas.append({**base, "type": "user", "uuid": self.uid(), "timestamp": iso(t),
                                   "message": {"role": "user", "content": self.r.choice(RUIDO)}})
            if estilo == "edita":            # builds without planning
                hs = [self.r.choice(["Edit", "Write", "Edit", "Read"])]
            elif estilo == "planifica":
                hs = ["TodoWrite"] if i == 0 else [self.r.choice(["Edit", "Read", "Grep"])]
            elif estilo == "bash":           # many shell calls, no skill
                hs = ["Bash"]
            else:
                hs = [self.r.choice(["Read", "Grep", "Bash", "Edit"])]
                if self.r.random() < 0.04:
                    hs.append("skill:" + self.r.choice(SKILLS_USADAS))
                if self.r.random() < 0.03:
                    hs.append("agente:code-reviewer")
                if self.r.random() < 0.05:
                    hs.append(self.r.choice(["mcp__github__create_issue", "mcp__playwright__navigate",
                                             "mcp__linear__list_issues"]))
            self.turno_asistente(
                lineas, base, t, modelo,
                cache_bueno=(proyecto != "notes-cli"),
                rapido=(modelo == "claude-opus-5" and self.r.random() < 0.05),
                herramientas=hs,
                salida=self.r.randint(900, 2400) if estilo == "maraton" else None,
            )
            t += dt.timedelta(seconds=self.r.randint(20, 140))
            if t > AHORA - dt.timedelta(minutes=5):
                break
        if tope:
            lineas.append({**base, "type": "system", "uuid": self.uid(), "timestamp": iso(t),
                           "message": {"quotaLimits": {
                               "status": "rejected", "rateLimitType": "five_hour",
                               "resetsAt": int((t + dt.timedelta(hours=2)).timestamp()),
                               "overageStatus": "disabled", "overageDisabledReason": "out_of_credits"}}})
        carpeta = self.casa / ".claude" / "projects" / CARPETA.format(proyecto)
        ruta = carpeta / f"{nombre or sid}.jsonl"
        self.escribir(ruta, "".join(json.dumps(x, ensure_ascii=False) + "\n" for x in lineas))
        return sid, carpeta, t

    def subagente(self, carpeta: Path, sid: str, proyecto: str, inicio: dt.datetime):
        base = {"sessionId": sid, "cwd": CWD.format(proyecto), "gitBranch": "main"}
        lineas: list[dict] = []
        t = inicio
        for _ in range(self.r.randint(6, 14)):
            self.turno_asistente(lineas, base, t, "claude-sonnet-5", herramientas=["Read"],
                                 sidechain=True)
            t += dt.timedelta(seconds=15)
        ruta = carpeta / sid / "subagents" / f"agent-{self.uid()[:8]}.jsonl"
        self.escribir(ruta, "".join(json.dumps(x) + "\n" for x in lineas))

    def claude_code(self):
        # 27 days of normal work, one or two sessions a day.
        for dias in range(27, 0, -1):
            for _ in range(self.r.choice([1, 1, 2])):
                dia = AHORA - dt.timedelta(days=dias, hours=self.r.randint(1, 10))
                reciente = dias <= 7
                proyecto = ("acme-webshop" if reciente and self.r.random() < 0.8
                            else self.r.choice(PROYECTOS))
                modelo = self.r.choices(
                    ["claude-opus-5", "claude-sonnet-5", "claude-haiku-4-5", "claude-lab-preview"],
                    weights=[6, 3, 1, 0.4])[0]
                estilo = ("edita" if reciente and self.r.random() < 0.5
                          else "bash" if dias <= 12 and self.r.random() < 0.25 else "normal")
                prompt = REPETIDO.format(proyecto) if dias <= 12 and self.r.random() < 0.35 else None
                sid, carpeta, _ = self.sesion_claude(proyecto, dia, self.r.randint(18, 60), modelo,
                                                     estilo=estilo, prompt_fijo=prompt)
                if self.r.random() < 0.3:
                    self.subagente(carpeta, sid, proyecto, dia + dt.timedelta(minutes=5))
        # Guaranteed repetitions for the pattern detector.
        for k in range(4):
            dia = AHORA - dt.timedelta(days=2 + k, hours=3)
            self.sesion_claude("ledger-api", dia, 12, "claude-sonnet-5",
                               prompt_fijo=REPETIDO.format("ledger-api"))
        # Sessions that build without a plan, and ones driven by Bash alone.
        for k in range(4):
            self.sesion_claude("acme-webshop", AHORA - dt.timedelta(days=1 + k, hours=5), 20,
                               "claude-opus-5", estilo="edita")
        for k in range(2):
            self.sesion_claude("notes-cli", AHORA - dt.timedelta(days=3 + k, hours=2), 32,
                               "claude-opus-5", estilo="bash")
        # A marathon session that also hits the 5-hour limit.
        self.sesion_claude("acme-webshop", AHORA - dt.timedelta(hours=30), 430, "claude-opus-5",
                           estilo="maraton", tope=True)
        # The file that --rotar will replace later.
        self.sesion_claude("ledger-api", AHORA - dt.timedelta(days=1, hours=2), 10,
                           "claude-sonnet-5", nombre="sesion-rotada")

    def rotar(self):
        ruta = (self.casa / ".claude" / "projects" / CARPETA.format("ledger-api")
                / "sesion-rotada.jsonl")
        antes = ruta.stat().st_ino if ruta.exists() else None
        tmp = ruta.with_suffix(".nuevo")
        self.r.seed(os.getpid())            # new content, new message ids
        carpeta = ruta.parent
        _, _, _ = self.sesion_claude("ledger-api", AHORA - dt.timedelta(hours=1), 8,
                                     "claude-haiku-4-5", nombre="sesion-rotada.nuevo")
        (carpeta / "sesion-rotada.nuevo.jsonl").rename(tmp)
        os.replace(tmp, ruta)               # same path, new inode
        print(f"rotated {ruta.name}: inode {antes} -> {ruta.stat().st_ino}")

    # ── Claude config, memory, inventory ─────────────────────────────────
    def claude_config(self):
        c = self.casa
        self.escribir(c / ".claude.json", json.dumps({
            "oauthAccount": {"organizationRateLimitTier": "default_claude_pro",
                             "organizationType": "claude_pro",
                             "subscriptionCreatedAt": "2026-01-15T09:00:00Z",
                             "hasExtraUsageEnabled": True,
                             "emailAddress": "demo@example.com"},
            "cachedExtraUsageDisabledReason": "out_of_credits",
            "claudeAiMcpEverConnected": ["claude.ai Notion", "claude.ai Linear", "claude.ai Gmail"],
            "mcpServers": {"github": {"command": "npx", "args": ["-y", "github-mcp"],
                                      "env": {"GITHUB_TOKEN": ""}}},
        }, indent=2))
        self.escribir(c / "projects" / "acme-webshop" / ".mcp.json", json.dumps({
            "mcpServers": {"playwright": {"command": "npx"},
                           "postgres-local": {"command": "docker", "env": {"PGPASSWORD": ""}}}
        }, indent=2))
        for i, s in enumerate(SKILLS):
            d = AHORA - dt.timedelta(days=5 + i * 3)
            self.escribir(c / ".claude" / "skills" / s / "SKILL.md",
                          f"---\nname: {s}\ndescription: Synthetic example skill ({s}).\n---\n\n# {s}\n", d)
        for a in AGENTES:
            self.escribir(c / ".claude" / "agents" / f"{a}.md",
                          f"---\nname: {a}\ndescription: Synthetic subagent.\nmodel: sonnet\n---\n")
        self.escribir(c / ".claude" / "plugins" / "installed_plugins.json", json.dumps({"plugins": {
            "lint-helper@example-market": [{"installPath": str(c / ".claude/plugins/cache/lint-helper"),
                                            "version": "1.2.0", "lastUpdated": iso(AHORA)}]}}))

    def memoria(self):
        c = self.casa
        notas = {
            # sistema claude-mem: per-project memory
            c / ".claude/projects" / CARPETA.format("acme-webshop") / "memory/MEMORY.md":
                ("Index: [[checkout-decisions]] · [[style-guide]]", 1),
            c / ".claude/projects" / CARPETA.format("acme-webshop") / "memory/checkout-decisions.md":
                ("We keep taxes server-side. See [[style-guide]].", 3),
            c / ".claude/projects" / CARPETA.format("acme-webshop") / "memory/style-guide.md":
                ("Use the design tokens. Contact: design@example.com", 26),
            c / ".claude/projects" / CARPETA.format("ledger-api") / "memory/MEMORY.md":
                ("Index: [[invoice-rules]] · [[old-deploy-notes]]", 14),
            c / ".claude/projects" / CARPETA.format("ledger-api") / "memory/invoice-rules.md":
                ("Invoices for Initech Corp use net-30.", 33),
            # an Obsidian-style vault (MOTOR_NOTAS)
            c / "Notes/00 Home.md": ("[[Projects]] · [[Reading list]] · [[Missing note]]", 0),
            c / "Notes/Projects.md": ("[[acme roadmap]] and [[ledger decisions]]", 2),
            c / "Notes/projects/acme roadmap.md": ("Q4: checkout v2. Back to [[Projects]]", 12),
            c / "Notes/projects/ledger decisions.md": ("Decision log. [[Projects]]", 40),
            c / "Notes/Reading list.md": ("Nothing here yet.", 61),
            # Hermes memories
            c / ".hermes/memories/user-profile.md": ("Prefers short answers.", 4),
            c / ".hermes/memories/session-2026-08-20.md": ("Old session summary.", 25),
        }
        for ruta, (texto, dias) in notas.items():
            self.escribir(ruta, f"# {ruta.stem}\n\n{texto}\n", AHORA - dt.timedelta(days=dias))

    # ── Codex ────────────────────────────────────────────────────────────
    def codex(self):
        for k in range(7):
            t = AHORA - dt.timedelta(days=2 + k * 3, hours=4)
            sid = self.uid()
            modelo = "gpt-5.6-preview" if k == 5 else "gpt-5-codex"
            proyecto = self.r.choice(PROYECTOS)
            ruta = (self.casa / ".codex/sessions" / t.strftime("%Y/%m/%d")
                    / f"rollout-{t.strftime('%Y-%m-%dT%H-%M-%S')}-{sid}.jsonl")
            lineas = [{"timestamp": iso(t), "type": "session_meta",
                       "payload": {"id": sid, "cwd": CWD.format(proyecto), "model": modelo}}]
            total = {"input_tokens": 0, "cached_input_tokens": 0, "output_tokens": 0,
                     "reasoning_output_tokens": 0, "total_tokens": 0}
            for i in range(self.r.randint(8, 20)):
                t += dt.timedelta(seconds=self.r.randint(30, 90))
                ult = {"input_tokens": self.r.randint(2_000, 9_000),
                       "cached_input_tokens": self.r.randint(10_000, 40_000),
                       "output_tokens": self.r.randint(200, 1_500),
                       "reasoning_output_tokens": self.r.randint(0, 800)}
                ult["total_tokens"] = ult["input_tokens"] + ult["output_tokens"]
                for key in total:
                    total[key] += ult[key]
                if i == 0:
                    lineas.append({"timestamp": iso(t), "type": "turn_context",
                                   "payload": {"model": modelo, "cwd": CWD.format(proyecto)}})
                lineas.append({"timestamp": iso(t), "type": "event_msg",
                               "payload": {"type": "token_count",
                                           "info": {"total_token_usage": dict(total),
                                                    "last_token_usage": ult}}})
            self.escribir(ruta, "".join(json.dumps(x) + "\n" for x in lineas))

    # ── Hermes and OpenClaw ──────────────────────────────────────────────
    def hermes(self):
        h = self.casa / ".hermes"
        h.mkdir(parents=True, exist_ok=True)
        db = h / "state.db"
        if db.exists():
            db.unlink()
        cx = sqlite3.connect(db)
        cx.executescript("""
            CREATE TABLE sessions (id TEXT PRIMARY KEY, source TEXT, model TEXT,
                                   session_key TEXT, display_name TEXT);
            CREATE TABLE messages (id INTEGER PRIMARY KEY, session_id TEXT, role TEXT,
                                   content TEXT, timestamp REAL, token_count INTEGER DEFAULT 0);
        """)
        titulos = ["Daily backlog summary", "Draft reply to vendor@example.com",
                   "Weekly metrics digest", "Research: queue backoff strategies",
                   "Reminder list", "Changelog draft for notes-cli"]
        for k, titulo in enumerate(titulos):
            sid = f"hs_{k:03d}"
            cx.execute("INSERT INTO sessions VALUES (?,?,?,?,?)",
                       (sid, "telegram" if k % 2 else "cli",
                        "nousresearch/hermes-4-70b" if k % 3 else "openai/gpt-5-mini",
                        f"demo:{k}", titulo))
            t = (AHORA - dt.timedelta(days=1 + k * 2)).timestamp()
            for m in range(self.r.randint(4, 16)):
                cx.execute("INSERT INTO messages (session_id, role, content, timestamp, token_count)"
                           " VALUES (?,?,?,?,0)",
                           (sid, "user" if m % 2 == 0 else "assistant", "synthetic message", t + m * 45))
        cx.commit()
        cx.close()
        self.escribir(h / "skills/.usage.json", json.dumps({
            "web-research": {"use_count": 9, "last_used_at": iso(AHORA - dt.timedelta(days=1)),
                             "created_at": "2026-07-01T10:00:00Z"},
            "daily-digest": {"use_count": 21, "last_used_at": iso(AHORA - dt.timedelta(hours=20)),
                             "created_at": "2026-07-03T10:00:00Z"},
            "pdf-summary": {"use_count": 0, "last_used_at": None, "created_at": "2026-08-01T10:00:00Z"},
        }, indent=2))

    def openclaw(self):
        self.escribir(self.casa / ".openclaw/openclaw.json", json.dumps({
            "agents": {"defaults": {"model": {"primary": "openrouter/anthropic/claude-sonnet-5"}},
                       "list": [{"id": "triage", "description": "Sorts inbound issues by label"},
                                {"id": "docs-writer", "description": "Drafts docs pages",
                                 "model": "openrouter/openai/gpt-5-mini"}]}}, indent=2))

    def launchd(self):
        carpeta = self.casa / "Library/LaunchAgents"
        agentes = {
            "com.example.motor.lector": {"RunAtLoad": True, "KeepAlive": True,
                                         "ProgramArguments": ["/usr/bin/python3",
                                                              "/opt/motor/lector/lector.py", "--bucle"]},
            "com.example.motor.sueno": {"StartCalendarInterval": {"Hour": 7, "Minute": 0},
                                        "ProgramArguments": ["/usr/bin/python3",
                                                             "/opt/motor/lector/sonar.py"]},
            "com.example.backup": {"StartInterval": 3600, "ProgramArguments": ["/usr/local/bin/backup"]},
        }
        for etiqueta, d in agentes.items():
            self.escribir(carpeta / f"{etiqueta}.plist", plistlib.dumps({"Label": etiqueta, **d}))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--casa", type=Path, default=RAIZ / "data" / "demo" / "home")
    ap.add_argument("--semilla", type=int, default=7)
    ap.add_argument("--rotar", action="store_true", help="only rotate the demo transcript")
    a = ap.parse_args()
    g = Gen(a.casa.resolve(), a.semilla)
    if a.rotar:
        g.rotar()
        return
    g.claude_config()
    g.claude_code()
    g.memoria()
    g.codex()
    g.hermes()
    g.openclaw()
    g.launchd()
    n = sum(1 for _ in g.casa.rglob("*") if _.is_file())
    print(f"synthetic home ready: {n} files under {a.casa}")


if __name__ == "__main__":
    main()
